apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gateway
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.network/frontend: "true"
        io.kompose.service: gateway
    spec:
      containers:
      - image: oriontravelr/api-gateway:1.0
        imagePullPolicy: ""
        name: gateway
        ports:
        - containerPort: 3000
        resources: {}
      hostname: gateway
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
